apiVersion: v1
kind: Secret
metadata:
  name: codemind-secrets
  namespace: codemind
type: Opaque
stringData:
  JWT_SECRET: "your-jwt-secret"
  OPENAI_API_KEY: "your-openai-api-key"
  GROQ_API_KEY: "your-groq-api-key"
  GEMINI_API_KEY: "your-gemini-api-key"
  PINECONE_API_KEY: "your-pinecone-api-key"
  PINECONE_INDEX_NAME: "codemind2"
  GITHUB_TOKEN: "your-github-token"